### ISSUE TITLE
Menu is overlapping sticky header in Vector 2022 skin

### ISSUE THREAD

**Issue by jdlrobson** [wikimedia-gadgets/MoreMenu#24]
Spun off of https://www.mediawiki.org/wiki/Talk:Reading/Web/Desktop_Improvements#Text_in_certain_dropdown_menus_displays_over_sticky_header_drop_down_menu,_and_time_is_misaligned
https://en.wikipedia.org/wiki/Abu_Ibrahim_al-Hashimi_al-Qurashi?useskin=vector-2022 (you need to be logged in)

<img width="1419" alt="Screen Shot 2022-02-04 at 3 16 18 PM" src="https://user-images.githubusercontent.com/148752/152615630-57eb0c04-4a55-4948-a507-6e1a9dab01a0.png">

it seems to have a   z-index: 99 via an inline style on p-page

<img width="320" alt="Screen Shot 2022-02-04 at 3 17 08 PM" src="https://user-images.githubusercontent.com/148752/152615668-88f3b50b-e682-4d0b-b159-b22bb7044d5f.png">

**Comment by MusikAnimal** [comment]
Fixed! Thanks for creating this issue.
