### ISSUE TITLE
Missing class for li element

### ISSUE THREAD

**Issue by libkoi** [wikimedia-gadgets/MoreMenu#28]
MoreMenu looks pretty weird on mediawiki.org, I thought this was caused by some changes in 1.39.0-wmf.22.
A workaround is to add `mw-list-item` class to all `<li>` element with `mm-item` and `mm-submenu-wrapper` classes. 
![image](https://user-images.githubusercontent.com/18418456/181360621-84933293-f6f3-40de-8834-c118ffc2addb.png)

**Comment by MusikAnimal** [comment]
I should probably get #26 merged! Will get this fixed ASAP. Thanks for the report.
