### ISSUE TITLE
More menu not compatible with evolved Vector 2022 zebra design

### ISSUE THREAD

**Issue by jdlrobson** [wikimedia-gadgets/MoreMenu#41]
Please see https://phabricator.wikimedia.org/T337893 for more information.

The Zebra design is currently enabled for 50% of users. Bucketing varies per project so if you can't get it on one wiki try another (I don't get it for en.wikipedia.org for example but do get it on he.wikipedia.org)

The A/B test is disabled on German Wikipedia so you can see it here: https://de.wikipedia.org/wiki/Spain?vectorzebradesign=1&useskin=vector-2022

**Comment by MusikAnimal** [comment]
Resolved https://phabricator.wikimedia.org/T337893#8991330
